language: c
group: stable
dist: precise
os: linux

env:
   - CFLAGS="-Wnull-dereference -Wnull-dereference -fpie -fstack-protector-strong -D_FORTIFY_SOURCE=2"
   - CFLAGS="-Werror -Wall -Weverything"

compiler:
   - clang
   - gcc

before_install:
  - sudo apt-get install -qq autotools-dev libidn11-dev
before_script:
  - ./autogen.sh
script: ./configure && make V=1 && make check V=1

